Device related service implementation
eclipse-arrowhead/ah5-core-java-spring pull request #15
Opened 2024-07-17 20:53 UTC by borditamas

2024-07-18 09:27 UTC, Katinka666 commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/ServiceRegistryConstants.java
> +	public static final String HTTP_API_OP_DEVICE_QUERY_PATH = "/device/query";
`public static final String HTTP_API_OP_DEVICE_QUERY_PATH = HTTP_API_OP_DEVICE_PATH + "/query";`
or:
```
public static final String HTTP_API_OP_DEVICE_PATH = "/device";
public static final String HTTP_API_OP_QUERY_PATH = "/query";
```

2024-07-18 09:59 UTC, Katinka666 commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/api/http/DeviceDiscoveryAPI.java
> +	@Operation(summary = "Delets device entry by name if exists")
Deletes

2024-07-18 10:06 UTC, Katinka666 commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/api/http/ManagementAPI.java
> +		logger.debug("createDevices started");
removeDevices started

2024-07-19 09:48 UTC, Katinka666 commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/DeviceDbService.java
> +		logger.debug("getByName started");
typo: "getByFilters started"

2024-07-19 09:48 UTC, Katinka666 commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/DeviceDbService.java
> +		logger.debug("getByName started");
typo: "getPage started"

2024-07-19 09:48 UTC, Katinka666 commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/DeviceDiscoveryService.java
> +		final DeviceRequestDTO normalized = new DeviceRequestDTO(
How about dedicating a separate class to Device normalization? (That applies to the lookupDevice method too. Same question for System normalization.)

2024-07-19 09:48 UTC, Katinka666 commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/validation/DeviceDiscoveryValidation.java
> +					throw new InvalidParameterException("Address list containd null element", origin);
typo: contained

2024-07-19 09:48 UTC, Katinka666 commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/validation/DeviceDiscoveryValidation.java
In multiple cases:

1. `IsEmpty()` is called on a list
2. if it returns false,` IsEmpty()` is called on each of it's elements.

It maybe worth to write a Utilities method for this purpose (something like `boolean ContainsEmpty(List<T>)`?)
Also could be used in ManagementValidation.java.

2024-07-19 09:48 UTC, Katinka666 commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/validation/address/AddressNormalizator.java
> +			if (flat.length() != MAC_DASH_OR_COLON_PARTS_LENGTH * 2) {
_2_ could be a constant

2024-07-19 09:48 UTC, Katinka666 commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/validation/address/AddressNormalizator.java
> +				groups[i] = flat.substring(startIdx, startIdx + 2);
same constant could be used here too

2024-07-19 09:48 UTC, Katinka666 commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/validation/address/AddressNormalizator.java
> +		final List<String> groups = new ArrayList<>(8);
`IPV6_SIZE` instead of `8`

2024-07-23 07:11 UTC, borditamas commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/DeviceDiscoveryService.java
> +		final DeviceRequestDTO normalized = new DeviceRequestDTO(
yes that's a good idea
we both should place them into a `eu.arrowhead.serviceregistry.service.normalization` package

2024-07-23 07:12 UTC, borditamas commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/validation/DeviceDiscoveryValidation.java
also a good thought

2024-07-24 09:25 UTC, Katinka666 approved these changes

2024-07-26 06:49 UTC, Katinka666 commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/ManagementService.java
> +	private List<DeviceRequestDTO> normalizeDeviceRequestDTOs(final List<DeviceRequestDTO> dtoList) {
This method should be placed in the eu.arrowhead.serviceregistry.service.normalization.DeviceDiscoveryNormalization class (maybe DeviceNormalization would be a better filename)

2024-07-26 09:58 UTC, Katinka666 commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/ManagementService.java
> +		final DeviceQueryRequestDTO normalized = dto == null ? new DeviceQueryRequestDTO(null, null, null, null, null)
There is a normalizeDeviceRequestDTOs() method. It may be worth to create a normalizeDeviceQueryRequestDTO() method too (and move them into the Normalization package).

2024-07-26 09:59 UTC, Katinka666 commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/ManagementService.java
> +	private List<DeviceRequestDTO> normalizeDeviceRequestDTOs(final List<DeviceRequestDTO> dtoList) {
Or create ManagementNormalization?

2024-07-29 07:40 UTC, borditamas commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/ManagementService.java
> +	private List<DeviceRequestDTO> normalizeDeviceRequestDTOs(final List<DeviceRequestDTO> dtoList) {
Yeah, I seem to have forgotten about the mgmt parts...
I vote for ManagementNormalization class to have normalization and validation stuffs per one service.

2024-07-29 07:41 UTC, borditamas commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/ManagementService.java
> +		final DeviceQueryRequestDTO normalized = dto == null ? new DeviceQueryRequestDTO(null, null, null, null, null)
same as here:
https://github.com/Aitia-IIOT/ah5-core-java-spring/pull/15#discussion_r1694745870

2024-07-29 08:00 UTC, Katinka666 commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/ManagementService.java
> +	private List<DeviceRequestDTO> normalizeDeviceRequestDTOs(final List<DeviceRequestDTO> dtoList) {
Yes, that would be better!

2024-07-29 08:02 UTC, Katinka666 commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/ManagementService.java
> +	private List<DeviceRequestDTO> normalizeDeviceRequestDTOs(final List<DeviceRequestDTO> dtoList) {
I will also create this class and put my mgmt normalization related methods there.

2024-07-29 08:34 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/api/http/DeviceDiscoveryAPI.java
> +			@ApiResponse(responseCode = Constants.HTTP_STATUS_BAD_REQUEST, description = Constants.SWAGGER_HTTP_400_MESSAGE, content = {
is it possible to return BAD_REQUEST in this case?

2024-07-29 08:42 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/entity/Device.java
> +	public static final String DEFAULT_SORT_FIELD = "createdAt";
maybe name should be the default

2024-07-29 11:18 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/DeviceDbService.java
> +							}
This is implemented as if the elements of the metadataRequirementList have AND relation with each other. According our skype meeting we should use OR relation.

2024-07-29 11:22 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/DeviceDbService.java
> +			for (final DeviceRequestDTO candidate : candidates) {
It is a minor note, but they are not candidates anymore, you just save them in the previous lines

2024-07-29 11:26 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/DeviceDbService.java
> +						"Device names already exists: " + existingNames);
typo: "Device names" => "Device with names"

2024-07-29 11:29 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/DeviceDbService.java
> +				final String notExists = deviceEntries.stream()
I think this should be the opposite. Go through the candidate names and find those that are not exists in the database.

2024-07-29 11:40 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/DeviceDiscoveryService.java
> +						.collect(Collectors.toSet());
put some delimiter between the two (a space is ok), because this is ugly.

2024-07-29 11:40 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/DeviceDiscoveryService.java
> +						.map(a -> a.getAddressType().name() + a.getAddress())
put some delimiter between the two (a space is ok), because this is ugly.

2024-07-29 11:41 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/DeviceDiscoveryService.java
> +								.map(a -> a.type() + a.address())
here as well

2024-07-29 11:43 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/DeviceDiscoveryService.java
> +		}
This is a good idea. We should do this everywhere in the service layer where we call db service methods. (I will add this to the log service.)

2024-07-29 11:45 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/DeviceDiscoveryService.java
> +	private DeviceDiscoveryNormalization normalizator;
I think the variable name should be normalizer.

2024-07-29 11:50 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/DeviceDiscoveryService.java
> +			return dtoConverter.convertDeviceAddressEntriesToDTO(entries, entries.size());
it is a confusing name. It does not convert device addresses only.

2024-07-29 11:51 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/ManagementService.java
> +	private AddressNormalizator addressNormalizator;
addressNormalizer

2024-07-29 11:58 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/normalization/DeviceDiscoveryNormalization.java
> +	private AddressNormalizator addressNormalizator;
Normalizator => normalizer everywhere

2024-07-29 12:02 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/validation/DeviceDiscoveryValidation.java
> +
should check the maximum size as well

2024-07-29 12:07 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/validation/ManagementValidation.java
> +				throw new InvalidParameterException("Address list contains null element or empty", origin);
"Device name list contains null element or empty" => "Device name list contains null or empty element"

2024-07-29 12:16 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/validation/address/AddressNormalizator.java
> +		if (!Utilities.isEmpty(parts.stream().filter(p -> p.length() != 2).collect(Collectors.toList()))) {
use the constant instead of hardcoded 2.

2024-07-29 12:17 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/validation/address/AddressNormalizator.java
> +		for (int i = 0; i < split.length; i++) {
++i

2024-07-29 12:17 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/validation/address/AddressNormalizator.java
> +				for (int j = 0; j < (IPV6_GROUP_LENGTH - candidateGroupLength); j++) {
++j

2024-07-29 12:18 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/validation/address/AddressNormalizator.java
> +			for (int i = 0; i < (IPV6_SIZE - candidateSize); i++) {
++i

2024-07-29 12:18 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/validation/address/AddressNormalizator.java
> +		for (int i = 0; i < IPV4_PARTS_LENGTH; i++) {
++i

2024-07-29 12:19 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/validation/address/AddressNormalizator.java
> +			return candidate; // NetworkAddressVerifier will filter it out
I don't find any NetworkAddressVerifier class in the project

2024-07-29 12:20 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/validation/address/AddressNormalizator.java
> +					return candidate; // NetworkAddressVerifier will filter it out
I don't find any NetworkAddressVerifier class in the project

2024-07-29 12:20 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/validation/address/AddressNormalizator.java
> +				return candidate; // NetworkAddressVerifier will filter it out
I don't find any NetworkAddressVerifier class in the project

2024-07-29 12:22 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/validation/address/AddressTypeValidator.java
> +			throw new InvalidParameterException(ERROR_MSG_PREFIX + address + " is not MAC");
MAC => MAC address

2024-07-29 12:23 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/validation/address/AddressTypeValidator.java
> +			throw new InvalidParameterException(ERROR_MSG_PREFIX + address + " is not IPV4");
we should use the following format in every exception message: IPv4 and IPv6

Also: IPV4 => IPv4 address

2024-07-29 12:24 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/validation/address/AddressTypeValidator.java
> +			throw new InvalidParameterException(ERROR_MSG_PREFIX + address + " is not IPV6");
IPV6 => IPv6 address

2024-07-29 12:26 UTC, rbocsi requested changes
see inline comments

2024-08-01 09:34 UTC, rbocsi approved these changes

2024-08-02 09:50 UTC, merged