Kj/system
eclipse-arrowhead/ah5-core-java-spring pull request #18
Opened 2024-09-02 21:40 UTC by Katinka666

2024-09-04 09:40 UTC, rbocsi commented on serviceregistry/pom.xml
> +	</dependencies>
This shouldn't be here. These dependencies are already in the parent's pom.

2024-09-04 09:44 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/api/http/ManagementAPI.java
> +					@Content(mediaType = MediaType.APPLICATION_JSON_VALUE, schema = @Schema(implementation = SystemListResponseDTO.class)) }),
These are the same. Need only one.

2024-09-04 10:37 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/api/http/ManagementAPI.java
> +		logger.debug("querySystems started, verbose = " + Boolean.toString(verbose));
log4j does not like string concatenation, use instead parameters in the message:
```
logger.debug("querySystems started, verbose = {}", verbose);
```

2024-09-04 11:52 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/repository/SystemRepository.java
> +	public Page<System> findAllByNameIn(final List<String> names, Pageable pageble);
missing final

2024-09-04 11:58 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/SystemDbService.java
> +							.version();
You do a very similar thing twice. I think you should just find the matching SystemRequestDTO once (ends the expression at the get()), and use its metadata() and version() methods on the same object.

2024-09-04 12:04 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/SystemDbService.java
> +	public SystemListResponseDTO createBulk(final List<SystemRequestDTO> candidates) {
This one should return List<System>

2024-09-04 12:05 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/SystemDbService.java
> +			return createSystemListResponseDTOs(systemEntities, systemEntities.size());
The conversion to dto should be in the service layer

2024-09-04 12:08 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/SystemDbService.java
> +	public SystemListResponseDTO updateBulk(final List<SystemRequestDTO> toUpdate) {
This one should not return DTO, but some data structure that contains the necessary entities, see in DeviceDbService: ` List<Entry<Device, List<DeviceAddress>>>`

2024-09-04 12:11 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/SystemDbService.java
> +				return createSystemListResponseDTOs(systemEntities, systemEntities.size());
The conversion to dto should be in the service layer

2024-09-04 12:18 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/SystemDbService.java
> +	public Optional<SystemRequestDTO> getByName(final String name) {
same as before. Do not return DTO

2024-09-04 12:21 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/SystemDbService.java
> +		synchronized (LOCK) {
we don't want any synchronized in a getter

2024-09-04 12:28 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/SystemDbService.java
> +	public SystemResponseDTO createSystemResponseDTO(final System system) {
this shouldn't be here but in the service layer with a parameter list that matches the new output of getByName().

2024-09-04 12:29 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/SystemDbService.java
> +	public SystemListResponseDTO getPageByFilters(final SystemQueryRequestDTO dto, final String origin) {
returns a Page (see example in DeviceDbService)

2024-09-04 12:31 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/SystemDbService.java
> +	private PageService pageService;
This one shouldn't be used here but in the service layer.

2024-09-04 12:32 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/SystemDbService.java
> +				synchronized (LOCK) {
no synchronized in getter

2024-09-04 12:41 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/SystemDbService.java
> +						}
The ordering of the ifs is not optimal. You should use the following order (from simple to difficult):

- address type
- addresses
- version
- device names
- metadata

Metadata should be the last because that one is difficult and if we can filter out a system before it means we don't have to check the metadata requirements for that system.

2024-09-04 12:48 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/SystemDbService.java
> +				.distinct()
maybe used the distinct() before the first collect, so you don't need the second stream() and collect().

2024-09-04 12:50 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/SystemDbService.java
> +			if (!existingDeviceNames.contains(candidateDeviceName) && candidateDeviceName != null) {
why do you need here the candidateDeviceName != null exression?

2024-09-04 12:51 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/SystemDbService.java
> +		if (notExistingDeviceNames.size() != 0) {
!notExistingDeviceNames.isEmpty() should be better

2024-09-04 12:55 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/SystemDbService.java
> +					final System system = systemRepo.findAllByNameIn(Arrays.asList(candidate.name())).getFirst();
just write a findByName method into the appropriate repositories

2024-09-04 12:56 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/SystemDbService.java
> +	private SystemListResponseDTO createSystemListResponseDTOs(final List<System> systems, final long pageSize) {
DTO creation should be in the service layer

2024-09-04 12:59 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/ManagementService.java
> +    @Value("${service.discovery.verbose}")
this one should be come from a constant.

2024-09-04 13:02 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/ManagementService.java
> +		logger.debug("querySystems started, verbose = " + verbose);
use message parameters here

2024-09-04 13:02 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/ManagementService.java
> +			return systemDbService.createBulk(normalized);
DTO conversion should be here

2024-09-04 13:05 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/ManagementService.java
> +			final SystemListResponseDTO result = systemDbService.getPageByFilters(normalized, origin);
DTO conversion should be here. It is also has considered the verbose requirement

2024-09-04 13:06 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/ManagementService.java
> +				final List<SystemResponseDTO> resultTerse = new ArrayList<>();
I must be stupid, but I don't know what resultTerse means.

2024-09-04 13:07 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/ManagementService.java
> +			return systemDbService.updateBulk(normalized);
DTO conversion should be here

2024-09-04 13:08 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/SystemDiscoveryService.java
> +    @Value("${service.discovery.verbose}")
use constant

2024-09-04 13:11 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/SystemDiscoveryService.java
> +	public Entry<SystemResponseDTO, Boolean> registerSystem(final SystemRequestDTO dto, final String origin) {
db services should not return dto, dto conversion should be here

2024-09-04 13:11 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/SystemDiscoveryService.java
> +
db services should not return dto, dto conversion should be here (that handles the verbose requirement as well)

2024-09-04 13:20 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/matching/AddressMatching.java
> +		final List<AddressDTO> temp2 = new ArrayList<>(addresses2);
temp2 is unnecessary since you don't modify addresses2 list

2024-09-04 13:20 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/matching/AddressMatching.java
> +		while (temp1Size != 0) {
It is better if temp1Size > 0

2024-09-04 13:24 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/matching/AddressMatching.java
> +	}
I don't understand why is this necessary. It seems to me that addresses.remove(required) does the same.

2024-09-04 13:28 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/normalization/ManagementNormalization.java
> +				dto.pagination(), //no need to normailze, because it will happen in the getPageRequest method
typo in comment normailze => normalize

2024-09-04 13:51 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/validation/ManagementValidation.java
> +			if (system.name().length() > ArrowheadEntity.VARCHAR_SMALL) {
should use Constants.SYSTEM_NAME_LENGTH instead

2024-09-04 13:53 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/validation/ManagementValidation.java
> +		}
I think it is not a problem if the dto is null in this case (the similar method about devices does not throw an exception).

2024-09-04 13:57 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/validation/ManagementValidation.java
> +		validateQuerySystems(dto, origin);
In this method you have to accept null dto as well (maybe returns an empty dto in this case without any filter)

2024-09-04 13:59 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/validation/SystemDiscoveryValidation.java
> +		final SystemLookupRequestDTO normalized = normalizer.normalizeSystemLookupRequestDTO(dto);
in this method you can have a null dto. In this case you may return an empty dto without any filter

2024-09-04 14:01 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/validation/version/VersionValidator.java
> +		logger.debug("Validate version started: " + version);
use message parameters

2024-09-04 14:05 UTC, rbocsi requested changes
see inline comments

2024-09-17 12:11 UTC, Katinka666 commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/SystemDbService.java
> +				.distinct()
I don't think it would make the same result, because the same device can be associated to different systems, and the device-system connections will be distinguished even if the device is the same.

2024-09-17 13:27 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/SystemDbService.java
> +				.distinct()
I think it is the same result, that is my point. It is the same result with less operations.

2024-09-17 13:32 UTC, Katinka666 commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/SystemDbService.java
> +				.distinct()
That is true. Sorry, I was looking at a different function.

2024-09-18 08:14 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/repository/DeviceSystemConnectorRepository.java
> +	public Optional<List<DeviceSystemConnector>> findBySystemIn(final List<System> system);
Do you need Optional here? In other cases we just use List return value, and in worst case it returns an empty list.

2024-09-18 08:25 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/SystemDbService.java
> +			final List<DeviceAddress> deviceAddresses = device == null ? new ArrayList<DeviceAddress>() : deviceAddressRepo.findAllByDevice(device);
use `List.of()` instead of `new ArrayList<DeviceAddress>()`

2024-09-18 08:28 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/SystemDbService.java
> +				Page<System> systemEntries = new PageImpl<System>(new ArrayList<System>());
too much System, use diamonds when possible:

`Page<System> systemEntries = new PageImpl<>(new ArrayList<>());`

2024-09-18 08:46 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/SystemDbService.java
> +							if (!Utilities.isEmpty(versions) && !systemRepo.findAllByVersionIn(versions).contains(system)) {
I didn't notice the first time, but: the contains() only works well if the System.equals() is right. Since we don't override the Object.equals() it returns true only if the two systems are the same object, which may be not the case. You have to override equals() in System in a way that two system is equals if their db id is the same.

2024-09-18 08:54 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/SystemDbService.java
> +									&& !deviceNames.contains(deviceSystemConnectorRepo.findBySystem(system).get().getDevice().getName())) {
I don't like here that you call the same db operation twice. Refactor this to something like that:
```
if (!Utilities.isEmpty(deviceNames)) {
    // do the deviceSystemConnectorRepo.findBySystem(system) once and assign to a local variable
   if ( /* checking optional and not contains here */ ) {
       continue;
  }
}
```

2024-09-18 08:58 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/SystemDbService.java
> +									if (MetadataRequirementsMatcher.isMetadataMatch(Utilities.fromJson(system.getMetadata(), new TypeReference<Map<String, Object>>() { }), (MetadataRequirementDTO) requirement)) {
`Utilities.fromJson(system.getMetadata(), new TypeReference<Map<String, Object>>() { })` should be do once before the loop

2024-09-18 09:02 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/SystemDbService.java
> +			final Map<String, Object> metadataRequirementList, final List<String> versions, final List<String> deviceNames) {
wrong parameter here: should be final List<MetadataRequirementDTO> metadataRequirementList

2024-09-18 09:04 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/SystemDbService.java
> +								for (final Map.Entry<String, Object> requirement : metadataRequirementList.entrySet()) {
wrong loop because of wrong parameter before: should be `for (final MetadataRequirementDTO requirement : metadataRequirementList) {`

2024-09-18 09:07 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/SystemDbService.java
> +								boolean metaDataMatch = false;
metaData => metadata everywhere

2024-09-18 09:15 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/SystemDbService.java
> +				final List<SystemAddress> systemAddresses = systemAddressRepo.findAllBySystemIn(systemEntries.toList());
It is better to use getContent() here instead of toList() because the latter one always create a new list (and you use if 3 times), while the former is not.

2024-09-18 09:16 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/SystemDbService.java
> +						? new ArrayList<DeviceSystemConnector>() : deviceSystemConnections.get());
use List.of() as first option here

2024-09-18 09:34 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/SystemDbService.java
> +
I think we misunderstood each other here. I have no problem with using lambda expression here, it is just not optimal (and also not handle null values).

```
final List<String> candidateDeviceNames = candidates.stream()
                                .filter(c -> c.deviceName() != null)
				.map(c -> c.deviceName())
				.distinct()
				.collect(Collectors.toList());
```

2024-09-18 09:37 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/SystemDbService.java
> +		final List<Triple<System, List<SystemAddress>, Entry<Device, List<DeviceAddress>>>> result = new ArrayList<Triple<System, List<SystemAddress>, Entry<Device, List<DeviceAddress>>>>();
on the right side you can use just a diamond: `new ArrayList<>()`.

2024-09-18 09:39 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/SystemDbService.java
> +			final List<DeviceAddress> deviceAddressList = device == null ? new ArrayList<DeviceAddress>() : deviceAddressRepo.findAllByDevice(device);
List.of() for creating an empty list

2024-09-18 09:44 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/ManagementService.java
> +    private static boolean verboseEnabled;
We misunderstand each other here. This member is not static, it is just in the ˙@Value˙ annotation I don't want to see string literals. '${service.discovery.verbose}' should be a constant in the ServiceRegistryConstants class (already have examples there) and here you just use the name of the constant.

2024-09-18 09:47 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/ManagementService.java
> +			return dtoConverter.convertSystemTripleListToDTO(entities);
I'd rename this method to convertSystemTripletListToDTO.

2024-09-18 09:51 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/ManagementService.java
> +					Utilities.isEmpty(normalized.metadataRequirementList()) ? new HashMap<String, Object>()
It seems to me you have overthinked this one. You just have to pass the normalized.metadataRequirementList() here. If it is null or empty list the dbService handles it.

2024-09-18 09:54 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/ManagementService.java
> +			final SystemListResponseDTO result = dtoConverter.convertSystemTriplesToDTO(page);
I'd rename this method to convertSystemTripletPageToDTO.

2024-09-18 09:55 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/ManagementService.java
> +			java.lang.System.out.println(result.count());
remove this line

2024-09-18 09:57 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/SystemDiscoveryService.java
> +    private static boolean verboseEnabled;
See my appropriate comment in the ManagementService class.

2024-09-18 09:58 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/SystemDiscoveryService.java
> +				final SystemResponseDTO existingSystemAsResponseDTO = dtoConverter.convertSystemTripleToDTO(existingSystem);
I'd rename this method to convertSystemTripletToDTO

2024-09-18 10:01 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/SystemDiscoveryService.java
> +							: Utilities.fromJson(Utilities.toJson(normalized.metadataRequirementList()), new TypeReference<Map<String, Object>>() { }),
see my relevant comment in ManagementService where you use getPageByFilters()

2024-09-18 10:47 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/SystemDiscoveryService.java
> +		if (!existingSystem.getMetadata().equals(Utilities.toJson(dto.metadata()))) {
this is wrong. The two metadata can be the same even if their string representation is not the same. You have to transform the string to Map<String, Object> and compare the two maps, not the other way.

2024-09-18 10:52 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/dto/DTOConverter.java
> +		final List<SystemResponseDTO> result = new ArrayList<>();
You can initialize the capacity of the ArrayList with entities entities.getSize()

2024-09-18 10:52 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/dto/DTOConverter.java
> +		final List<SystemResponseDTO> result = new ArrayList<>();
You can initialize the capacity of the ArrayList with entities entities.getSize()

2024-09-18 10:54 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/dto/DTOConverter.java
> +		final List<SystemResponseDTO> terse = new ArrayList<SystemResponseDTO>();
You can initialize the capacity of the ArrayList with verbose.entries().getSize()

2024-09-18 10:57 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/normalization/ManagementNormalization.java
> +					new ArrayList<MetadataRequirementDTO>(),
List.of() for empty list, but I think that null should suffice as well.

2024-09-18 10:58 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/normalization/SystemDiscoveryNormalization.java
> +			return new SystemLookupRequestDTO(null, null, null, new ArrayList<MetadataRequirementDTO>(), null, null);
List.of() for empty list, but I think that null should suffice as well.

2024-09-18 11:01 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/validation/ManagementValidation.java
> +			}
I think it should be possible to just filtering some addresses without specifying the type.

2024-09-18 11:02 UTC, rbocsi requested changes
see inline comments. I found new problems.

2024-09-20 11:20 UTC, Katinka666 commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/ManagementService.java
> +    private static boolean verboseEnabled;
And is it ok if I pull it from the application.properties file in ServiceRegistryConstans?

2024-09-20 11:24 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/ManagementService.java
> +    private static boolean verboseEnabled;
No, you use the annotation here, you just create a constants there.

Here is an example:
```
	public static final String ALLOW_SELF_ADDRESSING = "allow.self.addressing";
	public static final String $ALLOW_SELF_ADDRESSING_WD = "${" + ALLOW_SELF_ADDRESSING + ":true}";
```

2024-09-20 14:32 UTC, Katinka666 commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/SystemDbService.java
> +							if (!Utilities.isEmpty(versions) && !systemRepo.findAllByVersionIn(versions).contains(system)) {
Can I use the following, since the system name is unique?
`systemRepo.findAllByVersionIn(versions).stream().map(s -> s.getName()).collect(Collectors.toList()).contains(system.getName())`

2024-09-20 15:10 UTC, Katinka666 commented
@rbocsi please review again

2024-09-23 07:02 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/SystemDbService.java
> +							if (!Utilities.isEmpty(versions) && !systemRepo.findAllByVersionIn(versions).contains(system)) {
Yes, it could work. But if you want to use system names there is a more concise version of it:
```
systemRepo.findAllByVersionIn(versions).stream().filter(s -> s.getName().equals(system.getName())).findAny().isPresent()
```

and you can remove the not operator if you change the isPresent() to isEmpty() in the expression.

2024-09-23 07:28 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/ServiceRegistryConstants.java
> +	public static final String $SERVICE_DISCOVERY_VERBOSE_WD = "${" + SERVICE_DISCOVERY_VERBOSE + ":true}";
default should be false

2024-09-23 07:29 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/SystemDbService.java
> +								Optional<DeviceSystemConnector> connection = deviceSystemConnectorRepo.findBySystem(system);
missing final

2024-09-23 07:29 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/SystemDbService.java
> +								Map<String, Object> systemMetadata = Utilities.fromJson(system.getMetadata(), new TypeReference<Map<String, Object>>() { });
missing final

2024-09-23 07:36 UTC, rbocsi approved these changes
I made some new comments, but those are minor issues. After you fix them, no further review is needed from me.

2024-09-23 11:11 UTC, borditamas approved these changes

2024-09-24 10:09 UTC, merged