Kj/service definition
eclipse-arrowhead/ah5-core-java-spring pull request #20
Opened 2024-09-28 13:04 UTC by Katinka666

2024-09-30 07:50 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/ServiceDefinitionDbService.java
> +		logger.debug("getServiceDefinitionEntities started...");
not the method name is referenced here

2024-09-30 07:51 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/ServiceDefinitionDbService.java
> +		synchronized (LOCK) {
I don't see a reason to use a LOCK just for reading from the db.

2024-09-30 07:54 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/dto/DTOConverter.java
> +		logger.debug("convertServiceDefinitionEntityListToDTO started...");
not matching with the method name

2024-09-30 07:56 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/validation/ManagementValidation.java
> +		logger.debug("validateGetServiceDefinitions started");
not matching with the method name

2024-09-30 07:59 UTC, rbocsi commented on serviceregistry/src/test/java/eu/arrowhead/serviceregistry/service/validation/NameValidatorTest.java
> +	@Disabled
no need to disable the existing tests

2024-09-30 08:00 UTC, rbocsi requested changes
see inline comments

2024-09-30 10:37 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/ServiceDefinitionDbService.java
> +		logger.debug("getPage started...");
It is good that you removed the syncronized block, but now you have an unused LOCK member, which should be removed as well.

2024-09-30 10:38 UTC, rbocsi approved these changes
Approved, but I found one small issue which should be fixed.

2024-10-02 09:41 UTC, borditamas approved these changes

2024-10-04 08:47 UTC, merged