Kj/config
eclipse-arrowhead/ah5-core-java-spring pull request #21
Opened 2024-09-29 18:28 UTC by Katinka666

2024-09-30 08:02 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/api/http/ManagementAPI.java
> +	@PostMapping(path = ServiceRegistryConstants.HTTP_API_OP_GET_CONFIG_PATH, produces = MediaType.APPLICATION_JSON_VALUE)
It is a GET

2024-09-30 08:02 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/api/http/ManagementAPI.java
> +					@Content(mediaType = MediaType.APPLICATION_JSON_VALUE, schema = @Schema(implementation = LogEntryListResponseDTO.class)) }),
It does not return a LogEntryListResponseDTO

2024-09-30 08:03 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/api/http/ManagementAPI.java
> +		final String origin = HttpMethod.POST.name() + " " + ServiceRegistryConstants.HTTP_API_MANAGEMENT_PATH + ServiceRegistryConstants.HTTP_API_OP_GET_CONFIG_PATH;
it is a GET

2024-09-30 08:29 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/ConfigService.java
> +	private boolean serviceDiscoveryVerbose;
I don't like the idea to extend this class whenever somebody needs an other property. Instead of this you should autowire the Environment bean that contains all the properties of the application.properties. You also need a set that contains the forbidden keys (db related keys, cert related key, everything we should not provide via the get-config endpoint).

Using the method we don't need to modify the code whenever a new property is introduced (only if the property is a secret one => in this case you have to extend the forbidden keys set).

2024-09-30 08:34 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/ConfigService.java
> +			// Empty input list means all is required
I know we said that if there is no input list that means all is required, but I changed my mind. For security reasons, I think the caller has to know what it wants.  

Also, if a key is invalid (or forbidden) we should just omit from the response, not send error back.

2024-09-30 08:35 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/normalization/ConfigNormalization.java
> +		}
Based on previous comment null or empty list should return an error.

2024-09-30 08:36 UTC, rbocsi requested changes
see inline comments

2024-10-01 07:44 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/ServiceRegistryConstants.java
> +			"authenticator.secret.key");
there are more cert related keys (just not appearing currently in the application.properties, because we don't use the cert authentication):

```
server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:certificates/sentinel-storage.p12
server.ssl.key-store-password=123456
server.ssl.key-alias=sentinel-storage.testcloud2.aitia.arrowhead.eu
server.ssl.key-password=123456
server.ssl.client-auth=need
server.ssl.trust-store-type=PKCS12
server.ssl.trust-store=classpath:certificates/truststore.p12
server.ssl.trust-store-password=123456

disable.hostname.verifier=false
```

2024-10-01 07:46 UTC, rbocsi approved these changes
Approved, but see my comment.

2024-10-02 09:42 UTC, borditamas approved these changes

2024-10-04 08:42 UTC, merged