ServiceDiscovery implementation
eclipse-arrowhead/ah5-core-java-spring pull request #26
Opened 2024-10-02 09:35 UTC by borditamas

2024-10-02 09:50 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/api/http/utils/ServiceLookupPreprocessor.java
> +		logger.debug("process started");
this method's name is not process

2024-10-02 09:51 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/api/http/utils/ServiceLookupPreprocessor.java
> +			return false;
Not really matters (request never will be null), but in this case the better option is to return true.

2024-10-02 10:01 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/entity/ServiceInstance.java
> +	public static final String DEFAULT_SORT_FIELD = "createdAt";
I think service instance id would be a better default. It would be sorted basically system name and service definition name and version alphabetically.

2024-10-02 12:02 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/ServiceInstanceDbService.java
> +						interfaceCandidate.properties().keySet().forEach(propName -> {
somewhere here you should check that at least one property is in the map

2024-10-02 12:23 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/ServiceInstanceDbService.java
> +				if (matching && filters.getAlivesAt() != null && serviceCandidate.getExpiresAt() != null && filters.getAlivesAt().isBefore(serviceCandidate.getExpiresAt())) {
i think the last condition is supposed to be the opposite.  There is no match if the expire time is before the alive time.

2024-10-02 12:29 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/ServiceInstanceDbService.java
> +			final Page<ServiceInstance> page = serviceInstanceRepo.findAllByIdIn(matchingIds, pagination);
Not sure if needed but I put a flush after the delete just to be safe.

2024-10-02 12:30 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/ServiceInterfaceTemplateDbService.java
> +		return templateRepo.findByName(name);
surround with the usual try-catch

2024-10-02 12:31 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/ServiceInterfaceTemplateDbService.java
> +		logger.debug("getByName started");
name - log message mismatch

2024-10-02 12:32 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/ServiceInterfaceTemplateDbService.java
> +		}
surround by the usual try-catch

2024-10-02 12:33 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/ServiceInterfaceTemplateDbService.java
> +	public List<ServiceInterfaceTemplateProperty> getPropertiesByName(final String name) {
I'd rename this method to getPropertiesByTemplateName, because at first I thought the name parameter is the name of a property, not a template.

2024-10-02 12:36 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/ServiceDiscoveryService.java
> +			final Entry<ServiceInstance, List<ServiceInstanceInterface>> instanceEntry = instanceDbService.createBulk(List.of(normalized)).getFirst();
This two lines should be in the db service in one transaction. Because if the new registration is failed, the old one does not come back.

2024-10-02 12:37 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/ServiceDiscoveryService.java
> +			for (MetadataRequirementDTO metadataReq : normalized.metadataRequirementsList()) {
Heresy :)
Missing final

2024-10-02 12:38 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/ServiceDiscoveryService.java
> +		}
Missing case: if there is no metadataRequirements you have to create one with the restricted discovery requirement

2024-10-02 12:40 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/ServiceDiscoveryService.java
> +			throw ex;
maybe add origin here too

2024-10-02 12:41 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/ServiceDiscoveryService.java
> +	public ServiceInstanceListResponseDTO lookupServices(final String requesterSystemName, final ServiceInstanceLookupRequestDTO dto, final boolean verbose, final boolean restricted, final String origin
why do you need the first parameter here?

2024-10-02 12:46 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/dto/DTOConverter.java
> +	public ServiceInstanceResponseDTO convertServiceInstanceEntityToDTO(final Entry<ServiceInstance, List<ServiceInstanceInterface>> instanceEntry, final Triple<System, List<SystemAddress>, Entry<Device
typo: systemTripet => systemTriplet

2024-10-02 12:50 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/model/ServiceLookupFilterModel.java
> +		instanceIds = Utilities.isEmpty(dto.instanceIds()) ? new HashSet<>() : dto.instanceIds().stream().map(id -> id).collect(Collectors.toSet());
why do you need a map method call that doing nothing?

2024-10-02 12:54 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/model/ServiceLookupFilterModel.java
> +		alivesAt = Utilities.isEmpty(dto.alivesAt()) ? null : Utilities.parseUTCStringToZonedDateTime(dto.alivesAt());
parse handles null or empty values too

2024-10-02 13:01 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/model/ServiceLookupFilterModel.java
> +	public void setInstanceIds(final Set<String> instanceIds) {
All the setters seems unnecessary to me. If you follow my advice regarding the constructor, all members (except policies) can be final. Policies can be final too if you use `addAll(<result of the ternary operator>)` on policies instead of assignment.

2024-10-02 13:08 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/normalization/ServiceDiscoveryNormalization.java
> +				dto.serviceDefinitionName().trim().toLowerCase(),
I we don't do this in case of system and device names, I think service definition names can be case sensitive too

2024-10-02 13:09 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/normalization/ServiceDiscoveryNormalization.java
> +										i.templateName().trim().toUpperCase(),
I'm not sure we want template names to be case insensitive.

2024-10-02 13:11 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/normalization/ServiceDiscoveryNormalization.java
> +				Utilities.isEmpty(dto.interfaceTemplateNames()) ? new ArrayList<>() : dto.interfaceTemplateNames().stream().map(i -> i.trim().toUpperCase()).toList(),
see above about template name case sensitivity

2024-10-02 13:11 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/normalization/ServiceDiscoveryNormalization.java
> +		logger.debug("normalizeServiceInstanceRequestDTO started");
wrong name in log message

2024-10-02 13:12 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/normalization/ServiceDiscoveryNormalization.java
> +		return instanceId.trim().toLowerCase();
see above about case sensitivity (system and service definition names)

2024-10-02 13:17 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/utils/ServiceInstanceIdUtils.java
> +	private static final String delimiter = "-";
Let's choose a different delimiter, since system names and service definition names can contains dash.
Example:
system: a-b, service: c => a-b-c-1.0.0
system: a, service: b-c => a-b-c-1.0.0

Good candidates: /  // : ::

2024-10-02 13:18 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/utils/ServiceInstanceIdUtils.java
> +	public static String retriveSystemNameFromInstaceId(final String instanceId) {
typo: retrive => retrieve

2024-10-02 13:19 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/utils/ServiceInstanceIdUtils.java
> +		return instanceId.split(delimiter)[0];
We should add another assert that a split to delimiter returns an array with length 3.

2024-10-02 13:20 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/validation/ServiceDiscoveryValidation.java
> +
We have to integrate the NameValidator that @Katinka666 implemented in the service-definition branch. We should use it on service definition names and i think template names as well.

2024-10-02 13:21 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/validation/ServiceDiscoveryValidation.java
> +		// TODO validate service definition naming convention
ok, I see you want to do the same thing. :)

2024-10-02 13:22 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/validation/ServiceDiscoveryValidation.java
> +				throw new InvalidParameterException("Expiration time has an invalide time format", origin);
typo (or maybe french): invalide -> invalid

2024-10-02 13:25 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/validation/ServiceDiscoveryValidation.java
> +				throw new InvalidParameterException("Alive time has an invalide time format", origin);
french again :)

2024-10-02 13:28 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/validation/ServiceDiscoveryValidation.java
> +				if (templateOpt.isPresent() && !Utilities.isEmpty(interfaceInstance.protocol())) {
I think the second part of this condition is not needed here but in the first nested if. If we find the template we want to check the properties regardless of the protocol field.

2024-10-02 13:29 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/validation/ServiceDiscoveryValidation.java
> +					if (!interfaceInstance.protocol().equals(templateOpt.get().getProtocol())) {
The second part of the previous if goes here as first part.

2024-10-02 13:40 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/validation/ServiceDiscoveryValidation.java
> +									final List<String> validatorWithArgs = Arrays.asList(templateProp.getValidator().split("\\|"));
Delimiter should be a constant.
I don't see why do you work with list when eventually you'll need an array.

2024-10-02 13:43 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/validation/ServiceDiscoveryValidation.java
> +												validatorWithArgs.size() <= 1 ? new String[0] : validatorWithArgs.subList(1, validatorWithArgs.size() - 1).toArray(new String[0]));
You can use Arrays.copyOfRange() instead of subList if you stick with the array.

2024-10-02 13:45 UTC, rbocsi requested changes
see inline comments.

2024-10-04 08:35 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/normalization/ServiceDiscoveryNormalization.java
> +										i.templateName().trim().toUpperCase(),
should be lowercase

2024-10-04 08:37 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/normalization/ServiceDiscoveryNormalization.java
> +										i.templateName().trim().toUpperCase(),
+ task: database script currently uses uppercase template names as well. Please fix it.

2024-10-06 15:24 UTC, Katinka666 commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/api/http/ServiceDiscoveryAPI.java
> +											description  = "Set true if you want the response to contains the system and device details. (It should be configured in the Application properties as well.)",
typo: to contain

2024-10-06 15:24 UTC, Katinka666 commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/api/http/utils/ServiceLookupPreprocessor.java
> +		return boolObject != null && Boolean.valueOf(boolObject.toString());
Based on Rajmund's comment, wouldn't true be the default if the boolObject is null?

2024-10-06 15:24 UTC, Katinka666 commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/ServiceDiscoveryService.java
> +				metadataReq.put(ServiceRegistryConstants.METADATA_KEY_UNRESTRICTED_DISCOVERY, true);
Souldn't the value of METADATA_KEY_UNRESTRICTED_DISCOVERY be "false" here, since the restricted flag was true?

2024-10-06 15:24 UTC, Katinka666 commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/ServiceDiscoveryService.java
> +			if (verbose) {
It can be combined with the previous expression:
```
if (verbose) {
   if (!sysInfo.isDiscoveryVerbose()) {
        throw new ForbiddenException("Verbose is not allowed", origin);
    }
//...
}
```

2024-10-07 06:53 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/api/http/utils/ServiceLookupPreprocessor.java
> +		return boolObject != null && Boolean.valueOf(boolObject.toString());
No, if the boolObject is null it means the filter does not filled it because the policy is open.

2024-10-07 06:56 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/ServiceDiscoveryService.java
> +				metadataReq.put(ServiceRegistryConstants.METADATA_KEY_UNRESTRICTED_DISCOVERY, true);
The key means that the service can lookup without any restriction (even if the lookup is restricted).

2024-10-07 07:56 UTC, borditamas commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/normalization/ServiceDiscoveryNormalization.java
> +				dto.serviceDefinitionName().trim().toLowerCase(),
It has been decided afterward: All names should be lower-case #27

2024-10-07 10:51 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/ServiceInterfaceTemplateDbService.java
> +		logger.debug("getPropertiesByName started");
name still not matching

2024-10-07 10:57 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/utils/ServiceInstanceIdUtils.java
> +		Assert.isTrue(split.length == parts, "Invalid instaceId");
typo: instace => instance

2024-10-07 10:59 UTC, rbocsi requested changes
I found some minor issues. You can merge after addressed them.

2024-10-07 12:24 UTC, merged