Interface template mgmt implementation
eclipse-arrowhead/ah5-core-java-spring pull request #30
Opened 2024-10-10 09:41 UTC by borditamas

+ some bugfix

2024-10-10 10:47 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/api/http/ManagementAPI.java
> +		logger.debug("queryInterfaceTemplates");
missing started

2024-10-10 11:00 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/ServiceInterfaceTemplateDbService.java
> +								+ property.validatorParams().stream().map(p -> p).collect(Collectors.joining(ServiceRegistryConstants.INTERFACE_PROPERTY_VALIDATOR_DELIMITER));
why do you need map that doing nothing?

2024-10-10 12:12 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/dto/DTOConverter.java
> +										return new ServiceInterfaceTemplatePropertyDTO(prop.getPropertyName(), prop.isMandatory(), validator, validatorParams);
I'd extract this to an other method. Too long for a map body for my taste.

2024-10-10 12:15 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/normalization/ManagementNormalization.java
> +		logger.debug("ServiceInterfaceTemplateQueryRequestDTO started");
not match with method name

2024-10-10 12:16 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/normalization/ManagementNormalization.java
> +		logger.debug("ServiceInterfaceTemplateQueryRequestDTO started");
not match with method name (not even close)

2024-10-10 12:16 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/normalization/ManagementNormalization.java
> +		Assert.notNull(dto, "normalizeServiceInterfaceTemplateListRequestDTO is null");
what?

2024-10-10 12:20 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/validation/ManagementValidation.java
> +		logger.debug("validateAndNormalizeQueryInterfaceTemplates started");
not matching with method name

2024-10-10 12:38 UTC, rbocsi requested changes
see inline comments

2024-10-10 14:22 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/validation/interf/InterfaceValidator.java
> +									interfaceInstance.properties().put(templateProp.getPropertyName(), normalizedProp);
I just found this problem when I try to register services with ApplicationInitListener. This one throws UnsupportedOperationException because the interfaceInstance.properties() is an immutable map which is makes sense since a record should be immutable.

2024-10-11 07:54 UTC, rbocsi approved these changes

2024-10-11 11:26 UTC, Katinka666 requested changes

2024-10-11 11:26 UTC, Katinka666 commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/validation/ManagementValidation.java
> +		try {
Should we add the _origin_ paramter to the `validateName` method too, so it will be coherent with the `validateNormalizedAddress` and the `validateNormalizedVersion` methods?

2024-10-11 11:26 UTC, Katinka666 commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/validation/ManagementValidation.java
> +						throw new InvalidParameterException("Interface template cointains null property", origin);
Typo: contains

2024-10-11 11:26 UTC, Katinka666 commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/validation/ManagementValidation.java
> +			interfaceValidator.validateNormalizedInterfaceTemplates(normalized.interfaceTemplates());
If we add the _origin_ as parameter to the `validateName`, we can do that here too with the `validateNormalizedInterfaceTemplates`.

2024-10-11 11:26 UTC, Katinka666 commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/validation/interf/InterfaceValidator.java
> +				if (Utilities.isEnumValue(prop.validator(), PropertyValidatorType.class)) {
I think a not operator is missing here. (should be `!Utilities.isEnumValue`)

2024-10-11 11:39 UTC, borditamas commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/validation/ManagementValidation.java
> +		try {
We did not pass the origin to these simple or 'primitive' validator methods, but yeah I should hide it into a private method like you did with `validateNormalizedAddress ` and `validateNormalizedVersion `

2024-10-11 11:45 UTC, borditamas commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/validation/interf/InterfaceValidator.java
> +				if (Utilities.isEnumValue(prop.validator(), PropertyValidatorType.class)) {
nice catch :)

2024-10-11 11:57 UTC, borditamas commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/validation/ManagementValidation.java
> +			interfaceValidator.validateNormalizedInterfaceTemplates(normalized.interfaceTemplates());
Same as above. So far we have been passing the origin only until the service validation layer and not until the single property validations.

I would keep this practice or if you don't agree we shuold change it everywhere (address, version, metadata etc...).

2024-10-11 12:07 UTC, Katinka666 commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/validation/ManagementValidation.java
> +			interfaceValidator.validateNormalizedInterfaceTemplates(normalized.interfaceTemplates());
That's fair, I agree, we should keep the practice.

2024-10-11 12:10 UTC, Katinka666 approved these changes

2024-10-11 13:22 UTC, merged