Kj/service instances
eclipse-arrowhead/ah5-core-java-spring pull request #34
Opened 2024-10-17 23:24 UTC by Katinka666

2024-10-18 08:54 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/api/http/ManagementAPI.java
> +					@Content(mediaType = MediaType.APPLICATION_JSON_VALUE, schema = @Schema(implementation = SystemListResponseDTO.class)) }),
return type is wrong here

2024-10-18 08:57 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/ServiceInstanceDbService.java
> +		logger.debug("createBulk started");
not matching with method name

2024-10-18 09:49 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/ServiceInstanceDbService.java
> +					serviceInstanceRepo.saveAndFlush(instance);
assign to instance to make sure instance's fields are up-to-date.

2024-10-18 09:53 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/ServiceInstanceDbService.java
> +						for (Entry<String, Object> property : (List<Entry<String, Object>>) dto.properties()) {
missing final

2024-10-18 10:00 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/ServiceInstanceDbService.java
> +						for (Entry<String, Object> property : (List<Entry<String, Object>>) dto.properties()) {
dto.properties() is a `Map<String, Object>`. I'm not sure that the cast is valid. You can use entrySet() method on the map, or you can see what Tomi did in similar situation (foreach()).

2024-10-18 10:03 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/ServiceInstanceDbService.java
> +				}
you can't change an existing interface, because that can be used by other services as well. If the protocol in the dto is set (it is optional) and it does not match with the existing template's protocol, just throw an exception.

2024-10-18 10:34 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/ServiceInstanceDbService.java
> +			Assert.isTrue(Utilities.isEnumValue(dto.policy(), ServiceInterfacePolicy.class), "Invalid service interface policy");
This assert should be checked as soon as possible.

2024-10-18 10:36 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/ServiceInstanceDbService.java
> +				});
This can be one lambda expression. You can use foreach on the result of filter directly.

2024-10-18 10:36 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/SystemDbService.java
> +		for (String name : names) {
missing final

2024-10-18 10:37 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/SystemDbService.java
> +		List<Triple<System, List<SystemAddress>, Entry<Device, List<DeviceAddress>>>> result = new ArrayList<>();
missing final

2024-10-18 10:37 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/SystemDbService.java
> +			Optional<Triple<System, List<SystemAddress>, Entry<Device, List<DeviceAddress>>>> optionalTriple = getByName(name);
missing final

2024-10-18 10:40 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/ManagementService.java
> +		final List<Triple<System, List<SystemAddress>, Entry<Device, List<DeviceAddress>>>> systemTriplets;
These can't be final because don't initialized and get values later.

2024-10-18 10:40 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/ManagementService.java
> +			synchronized (LOCK) {
I think this syncronized here is unnecessary.

2024-10-18 11:01 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/ManagementService.java
> +			final List<Triple<System, List<SystemAddress>, Entry<Device, List<DeviceAddress>>>> systemTriplets;
unnecessary finals

2024-10-18 11:03 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/ManagementService.java
> +			synchronized (LOCK) {
I think this syncronized here is unnecessary.

2024-10-18 11:04 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/ManagementService.java
> +			synchronized (LOCK) {
I think this syncronized here is unnecessary.

2024-10-18 11:07 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/api/http/ManagementAPI.java
> +					description  = "Set true if you want the response to contain the system and device details. (It should be configured in the Application properties as well.)",
The part between the parantheses are not true in a management service operation.

2024-10-18 11:08 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/ManagementService.java
> +	private static final Object LOCK = new Object();
I think you don't need this lock.

2024-10-18 11:09 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/dto/DTOConverter.java
> +		final List<ServiceInstanceResponseDTO> entries = new ArrayList<>();
you can initialize the arraylist capacity here.

2024-10-18 11:11 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/dto/DTOConverter.java
> +		return new ServiceLookupFilterModel(new ServiceInstanceLookupRequestDTO(
missing logger debug message

2024-10-18 11:12 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/normalization/ManagementNormalization.java
> +		logger.debug("normalizeUpdateServiceInstanceIds started");
message not match with method name

2024-10-18 11:15 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/normalization/ManagementNormalization.java
> +	public ServiceInstanceRequestDTO normalizeServiceInstanceRequestDTO(final ServiceInstanceRequestDTO dto) {
it this public? because it is in the assistant methods part.

also missing starter debug message

2024-10-18 11:15 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/normalization/ManagementNormalization.java
> +	public ServiceInstanceUpdateRequestDTO normalizeServiceInstanceUpdateRequestDTO(final ServiceInstanceUpdateRequestDTO dto) {
it this public? because it is in the assistant methods part.

also missing starter debug message

2024-10-18 11:17 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/normalization/ManagementNormalization.java
> +				dto.instanceId().trim(),
you should use a name normalizer on this (beacuse system name and service definition name are normalized, and this one contains them)

2024-10-18 11:18 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/validation/ManagementValidation.java
> +		for (ServiceInstanceRequestDTO instance : dto.instances()) {
missing final

2024-10-18 11:20 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/validation/ManagementValidation.java
> +		for (ServiceInstanceUpdateRequestDTO instance : dto.instances()) {
missing final

2024-10-18 11:21 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/validation/ManagementValidation.java
> +		List<String> instanceIds = new ArrayList<>();
should be set

2024-10-18 11:24 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/validation/ManagementValidation.java
> +			if (instanceIds.contains(instance.instanceId())) {
normalize instanceid before checking for duplication (to avoid duplicates that only different because of lowercase-uppercase letters) and always add the normalized value to the instanceIds.

2024-10-18 11:31 UTC, rbocsi requested changes
see inline comments

2024-10-21 07:50 UTC, Katinka666 commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/ManagementService.java
> +			synchronized (LOCK) {
What happens if I create the instanceEntries (line 321), than someone deletes some, so the systemTriplets (line 322) will not contain the matching system? Sould I check this in the dtoConverter?

2024-10-21 18:02 UTC, Katinka666 commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/validation/ManagementValidation.java
> +			if (instanceIds.contains(instance.instanceId())) {
Sould I do this change in other methods too where we perform duplication check?

2024-10-21 18:21 UTC, Katinka666 commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/validation/ManagementValidation.java
> +		for (ServiceInstanceUpdateRequestDTO instance : dto.instances()) {
Next time I will not forget about them!

2024-10-24 07:18 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/validation/ManagementValidation.java
> +			if (instanceIds.contains(instance.instanceId())) {
If somewhere we check for duplicates before normalization, then yes. We introduce this lowercase transformation not too long ago, so it is possible we don't change duplication check code.

2024-10-28 10:45 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/ServiceInstanceDbService.java
> +				if (!template.getProtocol().equals(dto.protocol())) {
- only have to check if dto.protocol() is not null or empty (when using existing templates, the protocol is not a mandatory field in the dto).
- use equalsIgnoreCase() instead of equals() just to be safe
-

2024-10-28 10:47 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/ServiceInstanceDbService.java
> +					throw new InvalidParameterException("The protocol can not be overwritten");
need a better exception message. We should use what Tomi used in a similar case:
`"Interface has different protocol than " + dto.templateName() + " template"`

2024-10-28 10:48 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/ServiceInstanceDbService.java
> +						.toList()
don't need this line. You can use forEach on a stream.

2024-10-28 10:52 UTC, rbocsi requested changes
see new comments

2024-10-30 08:02 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/ServiceInstanceDbService.java
> +				if (!Utilities.isEmpty(dto.protocol())) {
This is not what I meant. In this case the protocol is not mandatory, but it can be specified. If it specified it has to be the same (using equalsIgnoreCase()) than the protocol in the existing template. So you have to combine the two condition.

2024-10-30 08:03 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/ServiceInstanceDbService.java
> +					throw new InvalidParameterException("The protocol for template with name " + dto.templateName()  + " already exists: " + template.getProtocol());
use the error message that Tomi used.

2024-10-30 08:03 UTC, rbocsi requested changes
see comments

2024-10-31 08:56 UTC, rbocsi approved these changes

2024-11-05 08:31 UTC, borditamas approved these changes

2024-11-05 08:40 UTC, merged