MQTT api
eclipse-arrowhead/ah5-core-java-spring pull request #37
Opened 2024-10-29 13:14 UTC by borditamas

2024-10-30 11:01 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/ServiceRegistryConstants.java
> +	public static final String MQTT_API_MONITOR_TOPIC = MQTT_API_BASE_TOPIC + "/management";
this is something else, maybe ends with /monitor?

2024-10-30 11:39 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/ServiceRegistrySystemInfo.java
> +				.serviceInterface(getMqttServiceInterfaceForDeviceDiscovery())
only add the MQTT interface if the MQTT is enabled.

2024-10-30 11:39 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/ServiceRegistrySystemInfo.java
> +				.serviceInterface(getMqttServiceInterfaceForSystemDiscovery())
only add the MQTT interface if the MQTT is enabled.

2024-10-30 11:39 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/ServiceRegistrySystemInfo.java
> +				.serviceInterface(getMqttServiceInterfaceForServiceDiscovery())
only add the MQTT interface if the MQTT is enabled.

2024-10-30 11:39 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/ServiceRegistrySystemInfo.java
> +				.serviceInterface(getMqttServiceInterfaceForServiceRegistryManagement())
only add the MQTT interface if the MQTT is enabled.

2024-10-30 12:03 UTC, rbocsi requested changes
see comments

2024-10-30 12:03 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/ServiceRegistrySystemInfo.java
> +			return null;
If you do this, you have to modify the Builder's serviceInterface method to not do anything if the input is null.

2024-10-30 12:03 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/api/mqtt/ManagementMqttHandler.java
> +			final Boolean verbose = Boolean.valueOf(request.getParams().get("verbose"));
use constant instead of string literal

2024-10-30 12:03 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/api/mqtt/ManagementMqttHandler.java
> +			 final Boolean verbose2 = Boolean.valueOf(request.getParams().get("verbose"));
use the constant

2024-10-30 12:03 UTC, rbocsi commented on serviceregistry/src/main/resources/database/default_inserts.sql
> +	'NOT_EMPTY_SET|NAME'
if we rename this enum, we have to modify here as well

2024-10-30 12:03 UTC, rbocsi commented on serviceregistry/src/main/resources/database/default_inserts.sql
> +	'NOT_EMPTY_SET|NAME'
if we rename this enum, we have to modify here as well

2024-10-30 12:15 UTC, rbocsi commented on serviceregistry/src/main/resources/application.properties
> +mqtt.client.password=123456
need to add these to the metadata file

2024-11-05 12:22 UTC, Katinka666 requested changes

2024-11-05 12:22 UTC, Katinka666 commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/api/mqtt/ManagementMqttHandler.java
> +			 final Boolean verbose2 = Boolean.valueOf(request.getParams().get("verbose"));
I would rename the `verbose2 `variable `service_query_verbose` and the `verbose` variable `system_query_verbose`

2024-11-05 12:22 UTC, Katinka666 commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/jpa/service/SystemDbService.java
> +		logger.debug("getByName started");
This was my mistake but we have to change this debug message to "getByNameList started" :)

2024-11-05 12:22 UTC, Katinka666 commented on serviceregistry/src/main/java/eu/arrowhead/serviceregistry/service/dto/DTOConverter.java
> +		logger.debug("convertServiceInstanceListToDTO started...");
This debug message is also wrong: convertServiceInstanceListToDTO -> convertServiceInstancePageToDTO

2024-11-22 13:40 UTC, rbocsi approved these changes

2024-11-22 13:46 UTC, Katinka666 approved these changes

2024-11-22 13:57 UTC, merged